import { AssessmentItem } from '@/lib/types';

const DEFAULT_GEMINI_KEY =
  process.env.NEXT_PUBLIC_GEMINI_API_KEY ||
  process.env.GEMINI_API_KEY ||
  '';

export const GEMINI_MODEL = 'gemini-3.5-flash-lite';

export type MathOperationType = 'sub' | 'add' | 'multiplication' | 'div';

export interface GeminiOCRResult {
  recognizedAnswers: Record<string, string>; // { q1: "25", q2: "33", ... }
  recognizedQuestions: AssessmentItem[]; // Extracted AssessmentItem[] questions from worksheet
  transcription: string;
  notes: string;
  confidence: number;
}

/**
 * Strips markdown code blocks and returns clean JSON string.
 */
function cleanJsonOutput(text: string): string {
  let cleaned = text.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.replace(/^```json\s*/, '').replace(/\s*```$/, '');
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```\s*/, '').replace(/\s*```$/, '');
  }
  return cleaned.trim();
}

/**
 * Generates 5 dynamic Multiple Choice Questions (MCQ) for primary FLN math using Gemini 3.5 Flash Lite.
 */
export async function generateDynamicQuestionsWithGemini(
  operation: MathOperationType = 'sub',
  apiKey: string = DEFAULT_GEMINI_KEY
): Promise<AssessmentItem[]> {
  const opPrompts: Record<MathOperationType, { name: string; desc: string; sample: string }> = {
    sub: {
      name: '2-digit subtraction with regrouping',
      desc: 'Minuends 50-99, Subtrahends 20-59 where the ones digit of minuend is SMALLER than subtrahend (e.g. 83 - 47). Distractors must include common errors like forgetting to decrement tens (e.g. 46 instead of 36) or reversing ones subtraction (e.g. 44).',
      sample: '83 − 47',
    },
    add: {
      name: '2-digit addition with regrouping',
      desc: '2-digit numbers (30-89) where ones sum to 10-18 (requiring carrying 1 ten into tens column). Distractors should include forgetting to carry the 1 ten.',
      sample: '58 + 27',
    },
    multiplication: {
      name: 'Multiplication facts & foundational 2-digit multiplication',
      desc: 'Multiplication facts for grades 3-4 (e.g. 7 x 8, 9 x 6, 12 x 4, 15 x 3). Distractors should include off-by-one multiplication slips or addition instead of multiplication.',
      sample: '7 × 8',
    },
    div: {
      name: 'Foundational division without remainder',
      desc: '2-digit numbers divided by 1-digit numbers with clean whole number quotients (e.g. 48 ÷ 6 = 8, 72 ÷ 8 = 9, 63 ÷ 7 = 9). Distractors should include adjacent quotients.',
      sample: '56 ÷ 7',
    },
  };

  const target = opPrompts[operation] || opPrompts.sub;

  const systemPrompt = `You are a premier Primary School FLN (Foundational Literacy and Numeracy) Math Assessment Specialist.
Generate exactly 5 distinct diagnostic multiple-choice questions (MCQs) for: ${target.name}.
Target level: Grade 3 / Grade 4 primary school learners.
Mathematical parameters: ${target.desc}.

For each question, formulate:
1. A clear vertical/horizontal prompt (e.g. "${target.sample}")
2. num1 (first number) and num2 (second number)
3. correctAnswer (integer)
4. Exactly 4 multiple-choice options (A, B, C, D):
   - One option MUST be the exact correctAnswer.
   - Three options MUST be realistic diagnostic distractors representing actual student misconceptions (e.g., failure to decrement tens, digit reversals, sign confusion).
5. Specify correctOptionId ("A", "B", "C", or "D").
6. Brief explanation.

Return ONLY a strictly valid JSON object matching this schema without any conversational text:
{
  "questions": [
    {
      "id": "q1",
      "order": 1,
      "prompt": "74 − 28",
      "num1": 74,
      "num2": 28,
      "correctAnswer": 46,
      "requiresRegrouping": true,
      "operation": "${operation === 'sub' ? 'subtraction' : operation === 'add' ? 'addition' : operation === 'multiplication' ? 'multiplication' : 'division'}",
      "targetSkill": "${target.name}",
      "description": "FLN diagnostic item generated by Gemini",
      "options": [
        { "id": "A", "value": 56, "text": "56", "misconception": "Borrowed without decrementing tens" },
        { "id": "B", "value": 46, "text": "46", "misconception": "none (correct)" },
        { "id": "C", "value": 54, "text": "54", "misconception": "Subtracted smaller ones from larger" },
        { "id": "D", "value": 44, "text": "44", "misconception": "Arithmetic recall slip" }
      ],
      "correctOptionId": "B"
    }
  ]
}`;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: systemPrompt }],
          },
        ],
        generationConfig: {
          temperature: 0.4,
          maxOutputTokens: 2048,
        },
      }),
    }
  );

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Gemini API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
  const cleaned = cleanJsonOutput(rawText);
  const parsed = JSON.parse(cleaned);

  interface RawGeminiOption {
    id: string;
    value?: number | string;
    text?: string;
    misconception?: string;
  }

  interface RawGeminiQuestion {
    prompt?: string;
    num1: number | string;
    num2: number | string;
    correctAnswer: number | string;
    requiresRegrouping?: boolean;
    operation?: string;
    targetSkill?: string;
    description?: string;
    options?: RawGeminiOption[];
    correctOptionId?: string;
  }

  // Format into standard AssessmentItem[]
  return (parsed.questions as RawGeminiQuestion[]).slice(0, 5).map((q: RawGeminiQuestion, idx: number) => ({
    id: `q${idx + 1}`,
    order: idx + 1,
    questionNumber: idx + 1,
    prompt: q.prompt || `${q.num1} ${operation === 'sub' ? '−' : operation === 'add' ? '+' : operation === 'multiplication' ? '×' : '÷'} ${q.num2}`,
    num1: Number(q.num1) || 0,
    operandA: Number(q.num1) || 0,
    num2: Number(q.num2) || 0,
    operandB: Number(q.num2) || 0,
    correctAnswer: Number(q.correctAnswer),
    requiresRegrouping: q.requiresRegrouping ?? true,
    operation: q.operation || (operation === 'sub' ? 'subtraction' : operation === 'add' ? 'addition' : operation === 'multiplication' ? 'multiplication' : 'division'),
    type: idx === 0 ? 'warmup' : 'diagnostic',
    targetSkill: q.targetSkill || target.name,
    description: q.description || `Diagnostic MCQ item #${idx + 1} generated by Gemini 3.5 Flash Lite`,
    options: (q.options || []).map((opt: RawGeminiOption) => ({
      id: opt.id,
      value: Number(opt.value) || Number(opt.text),
      text: String(opt.text ?? opt.value),
      misconception: opt.misconception,
    })),
    correctOptionId: q.correctOptionId || 'B',
  }));
}

/**
 * Performs Handwriting OCR on a student's assessment worksheet using Gemini 3.5 Flash Lite Vision.
 * Extracts BOTH the mathematical questions/problems AND the student's handwritten responses.
 */
export async function performGeminiVisionOCR(
  imageBase64: string,
  mimeType: string = 'image/jpeg',
  apiKey: string = DEFAULT_GEMINI_KEY
): Promise<GeminiOCRResult> {
  // Strip header data:image/jpeg;base64, if present
  const cleanBase64 = imageBase64.replace(/^data:image\/[a-z]+;base64,/, '');

  const prompt = `You are a specialized Educational Handwriting OCR Assistant for classroom math assessments.
Analyze this student's handwritten math worksheet or assessment paper.
Extract BOTH the math questions/problems AND the student's handwritten final answers for each question (e.g. Questions 1 through 5, or Q1 to Q5).

For each question:
1. Extract the full math question prompt (e.g. "52 − 27" or "58 + 27" or "7 × 8" or "56 ÷ 7").
2. Extract the numbers: num1 and num2.
3. Identify the operation: "subtraction", "addition", "multiplication", or "division".
4. Calculate the mathematically correct answer (correctAnswer as integer).
5. Extract the student's handwritten answer (studentAnswer as string, e.g. "46", "33", "25").
Pay special attention to handwritten digits (such as 46, 33, 25, 38, 45).
If a student wrote an answer like 46 for 83 - 47, accurately capture 46.

Return ONLY a strictly valid JSON object matching this schema without markdown fences or other text:
{
  "questions": [
    {
      "id": "q1",
      "order": 1,
      "prompt": "52 − 27",
      "num1": 52,
      "num2": 27,
      "operation": "subtraction",
      "correctAnswer": 25,
      "studentAnswer": "25"
    },
    {
      "id": "q2",
      "order": 2,
      "prompt": "71 − 38",
      "num1": 71,
      "num2": 38,
      "operation": "subtraction",
      "correctAnswer": 33,
      "studentAnswer": "33"
    },
    {
      "id": "q3",
      "order": 3,
      "prompt": "83 − 47",
      "num1": 83,
      "num2": 47,
      "operation": "subtraction",
      "correctAnswer": 36,
      "studentAnswer": "46"
    },
    {
      "id": "q4",
      "order": 4,
      "prompt": "64 − 26",
      "num1": 64,
      "num2": 26,
      "operation": "subtraction",
      "correctAnswer": 38,
      "studentAnswer": "38"
    },
    {
      "id": "q5",
      "order": 5,
      "prompt": "92 − 57",
      "num1": 92,
      "num2": 57,
      "operation": "subtraction",
      "correctAnswer": 35,
      "studentAnswer": "45"
    }
  ],
  "recognizedAnswers": {
    "q1": "25",
    "q2": "33",
    "q3": "46",
    "q4": "38",
    "q5": "45"
  },
  "transcription": "Detailed description of what the student wrote on the page, including any crossed out digits or scratch work.",
  "notes": "Student handwriting analysis notes (e.g. 'Clear pencil strokes, Question 3 has answer 46 with no tens decrement visible').",
  "confidence": 95
}`;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: prompt },
              {
                inlineData: {
                  mimeType,
                  data: cleanBase64,
                },
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.1,
          maxOutputTokens: 2048,
        },
      }),
    }
  );

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Gemini Vision OCR Error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
  const cleaned = cleanJsonOutput(rawText);
  const parsed = JSON.parse(cleaned);

  interface RawOcrQuestion {
    id?: string;
    order?: number;
    prompt?: string;
    num1?: number | string;
    num2?: number | string;
    operation?: string;
    correctAnswer?: number | string;
    studentAnswer?: number | string;
    requiresRegrouping?: boolean;
    targetSkill?: string;
    description?: string;
  }

  // Parse questions into standard AssessmentItem[]
  const rawQuestions: RawOcrQuestion[] = Array.isArray(parsed.questions) ? parsed.questions : [];
  const recognizedQuestions: AssessmentItem[] = rawQuestions.slice(0, 5).map((q: RawOcrQuestion, idx: number) => {
    const num1 = Number(q.num1) || 0;
    const num2 = Number(q.num2) || 0;
    const op = q.operation || 'subtraction';
    let correct = Number(q.correctAnswer);
    if (isNaN(correct)) {
      if (op === 'addition' || op === 'add') correct = num1 + num2;
      else if (op === 'multiplication' || op === 'mult') correct = num1 * num2;
      else if (op === 'division' || op === 'div') correct = Math.floor(num1 / (num2 || 1));
      else correct = num1 - num2;
    }
    const opSymbol = op.includes('add') ? '+' : op.includes('mult') ? '×' : op.includes('div') ? '÷' : '−';
    const prompt = q.prompt || `${num1} ${opSymbol} ${num2}`;

    return {
      id: q.id || `q${idx + 1}`,
      order: idx + 1,
      questionNumber: idx + 1,
      prompt,
      num1,
      operandA: num1,
      num2,
      operandB: num2,
      correctAnswer: correct,
      requiresRegrouping: q.requiresRegrouping ?? true,
      operation: op,
      type: idx === 0 ? 'warmup' : 'diagnostic',
      targetSkill: q.targetSkill || `Worksheet FLN ${op}`,
      description: q.description || `Worksheet question #${idx + 1} extracted by Gemini Vision OCR`,
    };
  });

  // Build recognizedAnswers from parsed.recognizedAnswers or parsed.questions
  const recognizedAnswers: Record<string, string> = parsed.recognizedAnswers || {};
  rawQuestions.forEach((q: RawOcrQuestion, idx: number) => {
    const qId = q.id || `q${idx + 1}`;
    if (q.studentAnswer !== undefined && !recognizedAnswers[qId]) {
      recognizedAnswers[qId] = String(q.studentAnswer);
    }
  });

  return {
    recognizedAnswers,
    recognizedQuestions,
    transcription: parsed.transcription || 'Handwritten mathematical response sheet.',
    notes: parsed.notes || 'Successfully analyzed via Gemini 3.5 Flash Lite Vision.',
    confidence: Number(parsed.confidence) || 94,
  };
}
